### PR TITLE
Rewrite website to match daudix-UFO mockup

### PR DESCRIPTION
**Pull request by tfuxu**
This is a complete rewrite of `gradienceisahack.github.io` website to match David Lapshin's (daudix-UFO) [mockup](https://github.com/GradienceTeam/Design/blob/main/Mockups/gradienceisahack.png), based on [Cantarell Typeface Family](https://gitlab.gnome.org/Teams/Design/cantarell.gnome.org) and [GNOME Circle](https://circle.gnome.org) websites source code.

## Changes include:
- New symbolics,
- Resized Gradience Devel logo,
- `README` update,
- `.vscode/` in .gitignore

~~I'm putting this PR as a draft for now, because I want to polish up some paddings, and check if removed all bugs.~~

### CODE REVIEW

**Comment by tfuxu** [comment]
Which one looks better?

With drop-shadow set to `offset-y: -0.08rem` and `radius: 0.4em`:
Screenshot from 2022-10-09 00-43-24

With drop-shadow set to `offset-y: 0.08rem` and `radius: 0.1em`:
Screenshot from 2022-10-09 00-43-40

**Comment by 0xMRTT** [comment]
second one i think

**Comment by daudix-UFO** [comment]
I feel like first one looks more like from GNOME website

**Comment by 0xMRTT** [comment]
image
 is that better ?

**Comment by tfuxu** [comment]
Nah, the current gradient is much better, beause it looks like a continuation of the gradient above IMO.

Edit: fixed

**Comment by tfuxu** [comment]
Also we don't need to put two more links to [stopthemingmy.app](https://stopthemingmy.app/), as we have a button dedicated to doing exactly what they do.

Edit: yes :D

**Comment by tfuxu** [comment]
c6612f20a80d47b25a533253274c7400eb6e0d5e Why?

Edit: fixed

**Comment by 0xMRTT** [comment]
image
mobile

**Comment by tfuxu** [comment]
> image mobile

I'll check that on my phone, because responsive design mode isn't always accurate.

**Comment by tfuxu** [comment]
f4e45b7ed0412d10ebbc35a1c36a9208416c842a
It was meant to look like a list of things. For example on https://circle.gnome.org/ `How it works` section with that text aligned to left
Screenshot from 2022-10-09 01-26-32

**Comment by daudix** [comment]
> [f4e45b7](https://github.com/gradienceisahack/gradienceisahack.github.io/commit/f4e45b7ed0412d10ebbc35a1c36a9208416c842a) It was meant to look like a list of things. For example on https://circle.gnome.org/ `How it works` section with that text aligned to left Screenshot from 2022-10-09 01-26-32

Agree, this was my idea

**Comment by tfuxu** [comment]
Okay, I think this was the last one.
Current width torelance is 360px, and I don't think we can go lower without making this site slightly ugly.

**Comment by daudix** [comment]
I will check everything one more time and we can merge

**Comment by daudix** [comment]
Noticed a few small things:

* Warning symbolic have wrong color, it need to be `dark4`

image

* Pattern are connected not very nicely

image

**Comment by daudix** [comment]
Alright, those things can be fixed by me, merging

**Comment by tfuxu** [comment]
1. Hmm, it is set to `--dark4`,
2. Yep, I know that, but I don't know for now how to make different y positions for lines in `background` properties

**Comment by daudix** [comment]
@tfuxu thank you for this very nice looking website ❤

**Comment by tfuxu** [comment]
Thank you for merging this, it was a lot of fun making it.

**Pull request merged**
